import enum


class PoseLandmark(enum.IntEnum):
    """The 33 pose landmarks."""
    NOSE = 0
    LEFT_EYE_INNER = 1
    LEFT_EYE = 2
    LEFT_EYE_OUTER = 3
    RIGHT_EYE_INNER = 4
    RIGHT_EYE = 5
    RIGHT_EYE_OUTER = 6
    LEFT_EAR = 7
    RIGHT_EAR = 8
    MOUTH_LEFT = 9
    MOUTH_RIGHT = 10
    LEFT_SHOULDER = 11
    RIGHT_SHOULDER = 12
    LEFT_ELBOW = 13
    RIGHT_ELBOW = 14
    LEFT_WRIST = 15
    RIGHT_WRIST = 16
    LEFT_PINKY = 17
    RIGHT_PINKY = 18
    LEFT_INDEX = 19
    RIGHT_INDEX = 20
    LEFT_THUMB = 21
    RIGHT_THUMB = 22
    LEFT_HIP = 23
    RIGHT_HIP = 24
    LEFT_KNEE = 25
    RIGHT_KNEE = 26
    LEFT_ANKLE = 27
    RIGHT_ANKLE = 28
    LEFT_HEEL = 29
    RIGHT_HEEL = 30
    LEFT_FOOT_INDEX = 31
    RIGHT_FOOT_INDEX = 32


class PoseConnection:
    """The pose landmark connections."""
    NOSE_TO_LEFT_EYE_INNER = (0, 1)
    LEFT_EYE_INNER_TO_LEFT_EYE = (1, 2)
    LEFT_EYE_TO_LEFT_EYE_OUTER = (2, 3)
    LEFT_EYE_OUTER_TO_LEFT_EAR = (3, 7)
    NOSE_TO_RIGHT_EYE_INNER = (0, 4)
    RIGHT_EYE_INNER_TO_RIGHT_EYE = (4, 5)
    RIGHT_EYE_TO_RIGHT_EYE_OUTER = (5, 6)
    RIGHT_EYE_OUTER_TO_RIGHT_EAR = (6, 8)
    MOUTH_LEFT_TO_MOUTH_RIGHT = (9, 10)
    LEFT_SHOULDER_TO_RIGHT_SHOULDER = (11, 12)
    LEFT_SHOULDER_TO_LEFT_ELBOW = (11, 13)
    LEFT_ELBOW_TO_LEFT_WRIST = (13, 15)
    LEFT_WRIST_TO_LEFT_PINKY = (15, 17)
    LEFT_WRIST_TO_LEFT_INDEX = (15, 19)
    LEFT_WRIST_TO_LEFT_THUMB = (15, 21)
    LEFT_PINKY_TO_LEFT_INDEX = (17, 19)
    RIGHT_SHOULDER_TO_RIGHT_ELBOW = (12, 14)
    RIGHT_ELBOW_TO_RIGHT_WRIST = (14, 16)
    RIGHT_WRIST_TO_RIGHT_PINKY = (16, 18)
    RIGHT_WRIST_TO_RIGHT_INDEX = (16, 20)
    RIGHT_WRIST_TO_RIGHT_THUMB = (16, 22)
    RIGHT_PINKY_TO_RIGHT_INDEX = (18, 20)
    LEFT_SHOULDER_TO_LEFT_HIP = (11, 23)
    RIGHT_SHOULDER_TO_RIGHT_HIP = (12, 24)
    LEFT_HIP_TO_RIGHT_HIP = (23, 24)
    LEFT_HIP_TO_LEFT_KNEE = (23, 25)
    RIGHT_HIP_TO_RIGHT_KNEE = (24, 26)
    LEFT_KNEE_TO_LEFT_ANKLE = (25, 27)
    RIGHT_KNEE_TO_RIGHT_ANKLE = (26, 28)
    LEFT_ANKLE_TO_LEFT_HEEL = (27, 29)
    RIGHT_ANKLE_TO_RIGHT_HEEL = (28, 30)
    LEFT_HEEL_TO_LEFT_FOOT_INDEX = (29, 31)
    RIGHT_HEEL_TO_RIGHT_FOOT_INDEX = (30, 32)
    LEFT_ANKLE_TO_LEFT_FOOT_INDEX = (27, 31)
    RIGHT_ANKLE_TO_RIGHT_FOOT_INDEX = (28, 32)
